#!/bin/bash

set -e

bin=$(dirname $0)

instance_id=`cat $bin/instance_id`
binding_id=`python -c 'import uuid; print str(uuid.uuid1())'`
`echo $binding_id > $bin/binding_id`

curl http://localhost:5001/v2/service_instances/$instance_id/service_bindings/$binding_id -u demouser:demopassword -d '{
  "plan_id":            "6ddf6b41-fb60-4b70-af99-8ecc4896b3cf",
  "service_id":         "2e2fc314-37b6-4587-8127-8f9ee8b33fea",
  "app_guid":   "5",
  "parameters": {}
}' -X PUT -H "X-Broker-API-Version: 2.8"  -H "Content-Type: application/json" -v
