#!/bin/bash

set -e

bin=$(dirname $0)

instance_id=`python -c 'import uuid; print str(uuid.uuid1())'`
`echo $instance_id > $bin/instance_id`

curl http://localhost:5001/v2/service_instances/$instance_id?accepts_incomplete=true -u demouser:demopassword -d '{
  "organization_guid":  "1",
  "plan_id":            "6b6fdd28-eb91-4eb7-9936-bf82ec1ec2d7",
  "service_id":         "47c6bff8-c653-4812-89f8-ee9a9b6c3d53",
  "space_guid":         "4",
  "parameters":         {},
  "accepts_incomplete": true
}' -X PUT -H "X-Broker-API-Version: 2.7" -H "Content-Type: application/json" -v
