#!/bin/bash

set -e

bin=$(dirname $0)

instance_id=`python -c 'import uuid; print str(uuid.uuid1())'`
`echo $instance_id > $bin/instance_id`

curl http://localhost:5001/v2/service_instances/$instance_id?accepts_incomplete=true -u demouser:demopassword -d '{
  "organization_guid":  "1",
  "plan_id":            "6ddf6b41-fb60-4b70-af99-8ecc4896b3cf",
  "service_id":         "2e2fc314-37b6-4587-8127-8f9ee8b33fea",
  "space_guid":         "4",
  "parameters":         {
    "resource_group_name": "binxi031401",
    "storage_account_name": "binxi031401sa"
  }
}' -X PUT -H "X-Broker-API-Version: 2.8" -H "Content-Type: application/json" -v
