#!/bin/bash

set -e

bin=$(dirname $0)

instance_id=`cat $bin/instance_id`
binding_id=`cat $bin/binding_id`

curl "http://localhost:5001/v2/service_instances/$instance_id/service_bindings/$binding_id?service_id=2e2fc314-37b6-4587-8127-8f9ee8b33fea&plan_id=6ddf6b41-fb60-4b70-af99-8ecc4896b3cf" -u demouser:demopassword -X DELETE -H "X-Broker-API-Version: 2.8" -v
